### PR TITLE
Add daily index stats

### PR DESCRIPTION
**Pull request by simmel**
Depends on #2

### CODE REVIEW

**Comment by iamtrump** [comment]
This implementation considers only one index per day — "logstash-*" and its name is hardcoded. I think it is not enough universal.

**Comment by simmel** [comment]
The index pattern can be made configurable. Since this is an ELK collectd plugin I'd figure people use the defaults for Logstash = )

If I refactor it to make the index pattern configurable, will you reconsider the patch then?

**Comment by iamtrump** [comment]
Yes, sure.

I think will be good to make new parameter, which will contain space separated list of indices with date mask in python format, for which daily stats will be fetched. Such like this:

```
Indices "syslog-%Y.%m.%d nginxlog-%Y-%m-%d"
```

Thank you for the contribution!

**Comment by simmel** [comment]
Cool! Could you tag a new version/release then?

**Comment by iamtrump** [comment]
Done.

**Pull request closed without merging**
